@host = http://localhost:3000
@apiPath = /api/comments

### 1. GET all comments
GET {{host}}{{apiPath}}
Accept: application/json

### 2. POST a new comment
# @name createComment
POST {{host}}{{apiPath}}
Content-Type: application/json

{
  "post_id": 101,
  "author": "Junior",
  "content": "This is a test comment from the HTTP client!"
}

### 3. GET the created comment by ID
@commentId = {{createComment.response.body.id}}
GET {{host}}{{apiPath}}/{{commentId}}
Accept: application/json

### 4. PUT (Update) the comment content
PUT {{host}}{{apiPath}}/{{commentId}}
Content-Type: application/json

{
  "content": "This comment has been updated via HTTP client."
}

### 5. DELETE the comment
DELETE {{host}}{{apiPath}}/{{commentId}}

### 6. Verify deletion (Should return 404)
GET {{host}}{{apiPath}}/{{commentId}}
Accept: application/json
